# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Alex Bucknall
description: "Personal Website of Alex Bucknall"
keywords: "Engineering, theme, free, download, SEO, blog, web"
url: http://bucknall.codes
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/bucknalla
disqus_shortname: "bucknall"
disqus_site_shortname: "bucknall"

# Author settings
author:
  name: Alex Bucknall
  job: PhD(c) Researcher @ WARC Lab, University of Warwick
  bio: "45% Researcher, 45% Engineer, 10% Day Dreamer. Working on Reconfigurable Computing, Adaptive Radio Networking and the Internet of Things."
  thumb: /images/alex.jpg
  email: alex.bucknall@gmail.com
  url: https://bucknall.codes
  github: https://github.com/bucknalla
  twitter: https://twitter.com/AlexRBucknall
  facebook: https://facebook.com/bucknalla
  linkedin: https://linkedin.com/in/bucknalla

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: contact
    title: Contact

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

future: true